#!/usr/bin/env sh
git submodule update --init --recursive || exit

( pkg update && pkg upgrade
	i() { pkg install "$@"; }

	i neovim tmux openssh
	i ranger fastfetch
echo )

( cd config; echo "config/"
	i() {
		echo "$2 -> $1"
		mkdir -p "$(dirname "$2")"
		ln -sfT "$PWD/$1" "$2"
	}; echo 'ln'
	i termux/ ~/.termux
	i bash/rc ~/.bashrc
	i bash/profile ~/.bash_profile
	i tmux ~/.tmux.conf
	i nvim/ ~/.config/nvim
	i fastfetch/ ~/.config/fastfetch
	i git ~/.gitconfig
	i ssh/config ~/.ssh/ssh_config
	i() {
		echo "$1 -> $2"
		sudo mkdir -p "$(dirname "$2")"
		sudo cp "$1" "$2"
	}; echo 'cp'
echo )

( cd etc; echo "etc/"
	termux-setup-storage
	termux-reload-settings
)
